name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compress code for transfer
        run: tar --exclude='./app.tar.gz' --exclude='./node_modules' --exclude='./.git' -czf app.tar.gz .

      - name: Copy code to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "app.tar.gz"
          target: "/home/andrew/review-bot/app.tar.gz"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/andrew/review-bot
            tar xzf app.tar.gz
            rm app.tar.gz
            cd app
            chmod +x deploy.sh
            ./deploy.sh
