name: Deploy to Server

on:
  push:
    branches:
      - main  # Запуск по пушу в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Подтягиваем код из репозитория

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4  # Настраиваем SSH для подключения к серверу
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy and Build on Server
      run: |
        tar czf - . | ssh -o StrictHostKeyChecking=no -p 2222 user@${{ secrets.SERVER_IP }} 'docker build -t telegram-bot:latest - && cd /home/andrew/review-bot && docker-compose down && docker-compose up -d'
