name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy code to server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: './'  # Путь к вашему коду в репозитории
          remote_path: '/home/andrew/review-bot'  # Путь на сервере, куда нужно скопировать код
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_port: ${{ secrets.SERVER_PORT }}
          ssh_private_key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            chmod +x deploy.sh
            ./deploy.sh
