name: Build and Deploy Docker Image via SSH

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t telegram-bot:latest .

      - name: Save Docker Image
        run: |
          docker save telegram-bot:latest | gzip > telegram-bot.tar.gz

      - name: Copy Docker Image to Server
        uses: appleboy/scp-action@v0.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "telegram-bot.tar.gz"
          target: "~/"

      - name: Load Docker Image and Restart Container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            docker load -i ~/telegram-bot.tar.gz
            docker stop telegram-bot || true
            docker rm telegram-bot || true
            docker run -d \
              --name telegram-bot \
              --env-file /home/andrew/review-bot/.env \
              telegram-bot:latest
