name: Deploy to Server

on:
  push:
    branches:
      - main  # Укажите вашу целевую ветку

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -p 2222 root@${{ secrets.SERVER_IP }} 'bash /home/andrew/review-bot/deploy.sh'
